/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;
import static JFrame.DBConnection.con;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author chrisjordan
 */
public class BMIPage extends javax.swing.JFrame {

    /**
     * Creates new form TrackPage
     */
    int userId;
    public BMIPage() {
        initComponents();
    }
// method to compute BMI and display result
public void computeAndDisplayBMI() {
    try {
        // Get user input for height and weight
        float height = Float.parseFloat(txt_height.getText());
        float weight = Float.parseFloat(txt_weight.getText());
        // Compute BMI
        float bmi = calculateBMI(height, weight);

        // Display the BMI result in a JTextArea
        txt_BMI.setText("        "+bmi+"        ");
        String remarks = getRemarks(bmi);
        txt_BMI_remarks.setText("Remarks: " + remarks);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for height and weight.");
    }
}

// method to calculate BMI
        private float calculateBMI(float height, float weight) {
            // BMI formula: weight (kg) / (height (m) * height (m))
            return weight / (height * height);
        }
        private String getRemarks(float bmi) {
            if (bmi < 18.5) {
                return "You are Underweight";
            } else if (bmi >= 18.5 && bmi <= 24.9) {
                return "You are Normal";
            } else if (bmi >= 25 && bmi <= 29.9) {
                return "You are Overweight";
            } else {
                return "You are Obese";
            }
            }
    private void uploadBMIToDatabase(float bmi) {
        try{
            if (SessionManager.isLoggedIn()) {
                User currentUser = SessionManager.getCurrentUser();
                userId = currentUser.getId();
                } else {
                JOptionPane.showMessageDialog(this, "unsuccessful");
            // Handle not logged in
             }
                // Establish database connection (update with your connection details)
                Connection con = DBConnection.getConnection();
                // Insert BMI into the database
                String sql = "INSERT INTO bmi (id, bmi_value) VALUES (?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1,userId);
                pst.setFloat(2,bmi);
            // Execute the insert query
                int rowsInserted = pst.executeUpdate();

                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "BMI uploaded to the database successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to upload BMI to the database.");
                }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error uploading BMI to the database:\n" + e.getMessage());
            e.printStackTrace();
        }
    }
    private void saveBMIToDatabase() {
        try {
            // Get the computed BMI from the JTextArea
            String bmiString = txt_BMI.getText().replace("                ", "");
            float bmi = Float.parseFloat(bmiString);

            // Upload BMI to the database
            uploadBMIToDatabase(bmi);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please compute BMI first.");
        }
    }
//FOR HOMEPAGE DISPLAY
    public class DatabaseHandler {
        private BMICallback callback;
        public DatabaseHandler(BMICallback callback) {
        this.callback = callback;
    }
        // Method to get the last inserted BMI value
        public double getLastInsertedBMI() {
            double lastBMI = 0.0;

            try (Connection con = DBConnection.getConnection();
                 Statement stmt = con.createStatement()) {

                String sql = "SELECT bmi_value FROM bmi ORDER BY bmi_id DESC LIMIT 1";
                ResultSet rs = stmt.executeQuery(sql);

                if (rs.next()) {
                    lastBMI = rs.getDouble("bmi_value");
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }

            return lastBMI;
        }
    }
    public interface BMICallback {
    void updateBMI(double lastBMI);
}
 //update 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        a_track = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        a_home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        a_bmi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        a_diet = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        a_water = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        a_logout = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_weight = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_height = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_BMI = new javax.swing.JTextArea();
        b_compute = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_BMI_remarks = new javax.swing.JTextArea();
        bmi_database = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 5, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SMART MACRO TRACKER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 310, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BMI CALCULATOR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 70));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a_track.setBackground(new java.awt.Color(51, 51, 51));
        a_track.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_trackMouseClicked(evt);
            }
        });
        a_track.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/icons8-write-50.png"))); // NOI18N
        jLabel1.setText("   TRACK");
        a_track.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 160, 60));

        jPanel3.add(a_track, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 350, 60));

        a_home.setBackground(new java.awt.Color(51, 51, 51));
        a_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_homeMouseClicked(evt);
            }
        });
        a_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/icons8-home-50.png"))); // NOI18N
        jLabel5.setText("   HOME PAGE");
        a_home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 180, 60));

        jPanel3.add(a_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 350, 60));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/icons8-analyze-50.png"))); // NOI18N
        jLabel8.setText("   ANALYZE");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 160, 60));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 60));

        a_bmi.setBackground(new java.awt.Color(0, 153, 153));
        a_bmi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/icons8-calculate-50.png"))); // NOI18N
        jLabel6.setText("   BMI CALCULATOR");
        a_bmi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 230, 60));

        jPanel3.add(a_bmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 350, 60));

        a_diet.setBackground(new java.awt.Color(51, 51, 51));
        a_diet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_dietMouseClicked(evt);
            }
        });
        a_diet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/icons8-diet-plan-48.png"))); // NOI18N
        jLabel7.setText("   DIET PLAN");
        a_diet.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 170, 60));

        jPanel3.add(a_diet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 350, 60));

        a_water.setBackground(new java.awt.Color(51, 51, 51));
        a_water.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_waterMouseClicked(evt);
            }
        });
        a_water.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/icons8-water-bottle-50.png"))); // NOI18N
        jLabel9.setText("   WATER TRACKER");
        a_water.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 220, 60));

        jPanel3.add(a_water, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 350, 60));

        a_logout.setBackground(new java.awt.Color(255, 0, 102));
        a_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_logoutMouseClicked(evt);
            }
        });
        a_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/icons8-logout-50.png"))); // NOI18N
        jLabel12.setText("   LOGOUT");
        a_logout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 60));

        jPanel3.add(a_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 350, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 780));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/smt_bmi_banner2.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 1000, 410));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Enter your Weight (in Kgs)");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, 47));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Your BMI is:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 47));

        txt_weight.setBackground(new java.awt.Color(153, 204, 255));
        txt_weight.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_weight.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel5.add(txt_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 247, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Enter your Height (in Meters)");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 47));

        txt_height.setBackground(new java.awt.Color(153, 204, 255));
        txt_height.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_height.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel5.add(txt_height, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 247, 50));

        jScrollPane1.setBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt_BMI.setBackground(new java.awt.Color(153, 204, 255));
        txt_BMI.setColumns(20);
        txt_BMI.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_BMI.setRows(5);
        txt_BMI.setAutoscrolls(false);
        jScrollPane1.setViewportView(txt_BMI);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, 60));

        b_compute.setBackground(new java.awt.Color(255, 0, 204));
        b_compute.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b_compute.setForeground(new java.awt.Color(255, 255, 255));
        b_compute.setText("COMPUTE");
        b_compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_computeActionPerformed(evt);
            }
        });
        jPanel5.add(b_compute, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txt_BMI_remarks.setBackground(new java.awt.Color(153, 204, 255));
        txt_BMI_remarks.setColumns(20);
        txt_BMI_remarks.setFont(new java.awt.Font("Segoe UI", 0, 31)); // NOI18N
        txt_BMI_remarks.setRows(5);
        txt_BMI_remarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_BMI_remarksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txt_BMI_remarks);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 460, 60));

        bmi_database.setBackground(new java.awt.Color(0, 204, 0));
        bmi_database.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bmi_database.setForeground(new java.awt.Color(255, 255, 255));
        bmi_database.setText("SAVE");
        bmi_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmi_databaseActionPerformed(evt);
            }
        });
        jPanel5.add(bmi_database, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 140, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 950, 300));

        setSize(new java.awt.Dimension(1478, 868));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a_trackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_trackMouseClicked
        // TODO add your handling code here:
                TrackPage track1 = new TrackPage();
                track1.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_a_trackMouseClicked

    private void a_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_homeMouseClicked
        // TODO add your handling code here:
                HomePage home1 = new HomePage();
                home1.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_a_homeMouseClicked

    private void b_computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_computeActionPerformed
        // TODO add your handling code here:
        computeAndDisplayBMI();
    }//GEN-LAST:event_b_computeActionPerformed

    private void bmi_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmi_databaseActionPerformed
        // TODO add your handling code here:
        saveBMIToDatabase();
    }//GEN-LAST:event_bmi_databaseActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        AnalyzePage a3 = new AnalyzePage();
        a3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void a_dietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_dietMouseClicked
        // TODO add your handling code here:
        DietPlanPage d3 = new DietPlanPage();
        d3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_a_dietMouseClicked

    private void a_waterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_waterMouseClicked
        // TODO add your handling code here:
        WaterTracker w3 = new WaterTracker();
        w3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_a_waterMouseClicked

    private void a_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_logoutMouseClicked
        // TODO add your handling code here:
        LoginPage l3 = new LoginPage();
         l3.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_a_logoutMouseClicked

    private void txt_BMI_remarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_BMI_remarksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BMI_remarksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMIPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMIPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a_bmi;
    private javax.swing.JPanel a_diet;
    private javax.swing.JPanel a_home;
    private javax.swing.JPanel a_logout;
    private javax.swing.JPanel a_track;
    private javax.swing.JPanel a_water;
    private javax.swing.JButton b_compute;
    private javax.swing.JButton bmi_database;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_BMI;
    private javax.swing.JTextArea txt_BMI_remarks;
    private javax.swing.JTextField txt_height;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
